# Generated by Django 2.2.7 on 2019-11-26 18:30

from django.db import migrations, models
import django.db.models.deletion
import sipeapps.auth.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('datahora_alteracao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'auth_perfil',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('datahora_alteracao', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(max_length=150, unique=True, validators=[sipeapps.auth.validators.UnicodeLoginValidator()])),
                ('senha', models.CharField(max_length=150)),
                ('nome_completo', models.CharField(blank=True, max_length=50)),
                ('apelido', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_ativo', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfil', to='auth.Perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('datahora_alteracao', models.DateTimeField(auto_now=True)),
                ('chave', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='auth.Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilPermissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('datahora_alteracao', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=200)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='auth.Perfil')),
            ],
            options={
                'db_table': 'auth_perfil_permissao',
                'unique_together': {('perfil', 'codigo')},
            },
        ),
    ]
