# Generated by Django 2.2.7 on 2019-11-26 18:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('datahora_alteracao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('datahora_alteracao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Física'), ('JURIDICA', 'Jurídica'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=13)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=255, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='')),
                ('contatos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('enderecos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('profissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='pessoa.Profissao')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
